### ISSUE TITLE
Supported Themes

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/theme-functions#12]
If you would like a theme supported on the official registry/theme servers please post below 

e.g. "I would like to see jsonresume-theme-awesome"

**Comment by bvosk** [comment]
Please add my theme, [jsonresume-theme-pumpkin](https://www.npmjs.com/package/jsonresume-theme-pumpkin).

Thank you!

**Comment by thomasdavis** [comment]
@bvosk Great work. I've added it -> https://registry.jsonresume.org/thomasdavis?theme=pumpkin

**Comment by lechuckcaptain** [comment]
Dear @thomasdavis would you be so kind to add also add my theme, [jsonresume-theme-cora](https://www.npmjs.com/package/jsonresume-theme-cora) to the official registry?

Thank you!

**Comment by thomasdavis** [comment]
@lechuckcaptain no worries. Theme looks great, added -> https://registry.jsonresume.org/thomasdavis?theme=cora

**Comment by 2xAA** [comment]
Hey @thomasdavis, would you be able to add my theme?
https://www.npmjs.com/package/jsonresume-theme-wraypro

Thanks!

**Comment by thomasdavis** [comment]
@2xAA https://registry.jsonresume.org/thomasdavis?theme=wraypro done

**Comment by souvikmaji** [comment]
Hi @thomasdavis, <https://www.npmjs.com/package/jsonresume-theme-elegant-jali> is a great looking theme. Can you please add it?

**Comment by thomasdavis** [comment]
@souvikmaji looks like it includes puppeteer which is too large of a dependency for us to include. Can you move it to dev dependencies?

**Comment by wahidshafique** [comment]
How about this one? 

https://www.npmjs.com/package/jsonresume-theme-wb-elegant

**Comment by mindyor** [comment]
I would like to see theme `shorter-bill`

**Comment by joeytall** [comment]
Hi @thomasdavis , I know you are a busy man, but can you take a quick minute add my theme, I made it very clean and professional.
https://www.npmjs.com/package/jsonresume-theme-joeytall
Would really appreciate it!

**Comment by thomasdavis** [comment]
hey @joeytall, I'm hesitant to include themes that are modifications of previous ones. Let me think about it for a bit

**Comment by joeytall** [comment]
Most themes supported so far are modifications of others(mainly elegant), so I don't see that as a problem.

**Comment by cedricdelpoux** [comment]
Could you make a list of supported themes? I'm not sure to understand how it works. For example, I'm able to use the [papirus theme](https://github.com/konalexiou/jsonresume-theme-papirus) but it's not listed here and not [the official listing](https://jsonresume.org/themes/) neither

**Comment by Suncatcher** [comment]
Support this, I also want to see list of available themes. Any theme I put throws _unsupported_. Where can I obtain a list of themes on server?

**Comment by thomasdavis** [comment]
Hi guys, I just pushed up a simply endpoint to list the current packages that the registry is deployed to handle -> https://registry.jsonresume.org/themes 

It will automatically update as new ones are added.

**Comment by EmaSuriano** [comment]
Hello, I would like to see  [jsonresume-theme-standard-resume](https://github.com/EmaSuriano/jsonresume-theme-standard-resume).

**Comment by thomasdavis** [comment]
Thanks @EmaSuriano, I do like that theme. Added.

https://registry.jsonresume.org/thomasdavis?theme=standard-resume

**Comment by veeravn** [comment]
@thomasdavis  Could you please add this theme https://github.com/veeravn/jsonresume-theme-tan-responsive.

**Comment by nickimola** [comment]
please add my theme:
https://www.npmjs.com/package/jsonresume-theme-nl-flat
thank you

**Comment by HeidiHansen** [comment]
Where can I preview these themes?  I'd really like to preview additional ones that aren't listed at https://jsonresume.org/themes/ but I'm not finding this anywhere.

**Comment by veeravn** [comment]
You will have to install the ones that aren't listed at jsonresume.org into you computer and run them locally using nodejs

**Comment by HeidiHansen** [comment]
So I take this as a 'no'.  It's really unfortunate that there aren't screenshots for these- It's cumbersome (if you want to try out many different ones) to install them before previewing.  =/

**Comment by ricosmall** [comment]
@thomasdavis Could you please add my theme [jsonresume-theme-apage](https://github.com/ricosmall/jsonresume-theme-apage)？Thanks.

**Comment by Snuggle** [comment]
I would love to see [jsonresume-theme-rocketspacer](https://github.com/rocketspacer/jsonresume-theme-rocketspacer/) by @rocketspacer, please!

**Comment by GordonRudman** [comment]
I would like to see jsonresume-theme-kwan-linkedin

**Comment by GordonRudman** [comment]
Please add my theme:
https://www.npmjs.com/package/jsonresume-theme-kwan-linkedin
Thank you

**Comment by thomasdavis** [comment]
@Snuggle I've added Rocket Spacer, looks good -> https://registry.jsonresume.org/theme/rocketspacer

@ricosmall Currently getting an error in your theme when running against default resume.json -> https://registry.jsonresume.org/theme/apage

**Comment by thomasdavis** [comment]
@HeidiHansen You are correct, it is annoying. Hopefully getting something out tonight to view examples of themes.

**Comment by mathieudutour** [comment]
@thomasdavis Could add https://github.com/mathieudutour/jsonresume-theme-github to the registry? Thank 🙏

**Comment by thomasdavis** [comment]
@mathieudutour good job, just getting the error 

```
TypeError: Cannot read property 'filter' of undefined
    at getExperiences (/srv/functions/node_modules/jsonresume-theme-github/index.js:218:10)
    at Object.Handlebars.registerHelper (/srv/functions/node_modules/jsonresume-theme-github/index.js:261:23)
```

You just need to defend against when someone doesn't have fields in their resume 

https://github.com/mathieudutour/jsonresume-theme-github/blob/master/index.js#L218 

The user doesn't have `experience` array.

**Comment by mathieudutour** [comment]
Ah right, should be fine now

**Comment by thomasdavis** [comment]
@mathieudutour Did you publish to npm again?

**Comment by thomasdavis** [comment]
Oh you did, ignore

**Comment by thomasdavis** [comment]
@mathieudutour Looks to be working -> https://registry.jsonresume.org/thomasdavis?theme=github 

I really liked the `pinned` attribute too, I think it might make a lot of sense to merge into the schema.

**Comment by thomasdavis** [comment]
@mathieudutour there is a 30 second render time that I can't figure out

**Comment by mathieudutour** [comment]
Hum not sure. Maybe the html minifier?

**Comment by veeravn** [comment]
@thomasdavis Could you please add this theme https://github.com/veeravn/jsonresume-theme-tan-responsive

Thank You

**Comment by thomasdavis** [comment]
Works well @veeravn good job -> https://registry.jsonresume.org/thomasdavis?theme=tan-responsive

**Comment by veeravn** [comment]
@thomasdavis I noticed that the size of the resume generated from my theme is a little off, so I was wondering what version of the theme that was published to the npm registry was used to generate the resume.

**Comment by thomasdavis** [comment]
@veeravn checkout the `functions/package.json` to see which version of your theme is active. 

Anyone who wants a theme added can also submit a PR with their theme added to the `package.json`

**Comment by veeravn** [comment]
@thomasdavis I didn't see my theme listed in the package.json file so I added it with the correct version and submitted this PR #14

**Comment by thomasdavis** [comment]
@veeravn My bad, the new repo is https://github.com/jsonresume/registry-functions/ 

I've gotta make a new issue on that repo...

**Comment by veeravn** [comment]
> @veeravn My bad, the new repo is https://github.com/jsonresume/registry-functions/
> 
> I've gotta make a new issue on that repo...

I created a PR in the registry-functions repo

**Comment by thomasdavis** [comment]
@veeravn deploying now, thanks!

**Comment by thomasdavis** [comment]
This repo will be deprecated from now on, continue discussion in the registry repo -> https://github.com/jsonresume/registry-functions/issues/7
